language: node_js

node_js:
    - "node"

install: # Install the dev dependencies
    - npm install -d

before_script: # Run the server in background
    - npm start &

after_script: # Stop the server launched
    - kill %1

